<?xml version="1.0" encoding="utf-8"?>
<variablelist xmlns:xlink="http://www.w3.org/1999/xlink">
  <varlistentry>
    <term><anchor xml:id="central-ftp"/>Төв серверүүд</term>
    <listitem>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.FreeBSD.org/pub/FreeBSD/">ftp://ftp.FreeBSD.org/pub/FreeBSD/</link> (ftp / ftpv6 / <link xlink:href="http://ftp.FreeBSD.org/pub/FreeBSD/">http://ftp.FreeBSD.org/pub/FreeBSD/</link> / <link xlink:href="http://ftp.FreeBSD.org/pub/FreeBSD/">http://ftp.FreeBSD.org/pub/FreeBSD/</link>) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-primary-ftp"/>Үндсэн толин тусгал сайтууд</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>mirror-admin@FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp1.FreeBSD.org/pub/FreeBSD/">ftp://ftp1.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp2.FreeBSD.org/pub/FreeBSD/">ftp://ftp2.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp3.FreeBSD.org/pub/FreeBSD/">ftp://ftp3.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp4.FreeBSD.org/pub/FreeBSD/">ftp://ftp4.FreeBSD.org/pub/FreeBSD/</link> (ftp / ftpv6 / <link xlink:href="http://ftp4.FreeBSD.org/pub/FreeBSD/">http://ftp4.FreeBSD.org/pub/FreeBSD/</link> / <link xlink:href="http://ftp4.FreeBSD.org/pub/FreeBSD/">http://ftp4.FreeBSD.org/pub/FreeBSD/</link>) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp5.FreeBSD.org/pub/FreeBSD/">ftp://ftp5.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp6.FreeBSD.org/pub/FreeBSD/">ftp://ftp6.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp7.FreeBSD.org/pub/FreeBSD/">ftp://ftp7.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp10.FreeBSD.org/pub/FreeBSD/">ftp://ftp10.FreeBSD.org/pub/FreeBSD/</link> (ftp / ftpv6 / <link xlink:href="http://ftp10.FreeBSD.org/pub/FreeBSD/">http://ftp10.FreeBSD.org/pub/FreeBSD/</link> / <link xlink:href="http://ftp10.FreeBSD.org/pub/FreeBSD/">http://ftp10.FreeBSD.org/pub/FreeBSD/</link>) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp11.FreeBSD.org/pub/FreeBSD/">ftp://ftp11.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp13.FreeBSD.org/pub/FreeBSD/">ftp://ftp13.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp14.FreeBSD.org/pub/FreeBSD/">ftp://ftp14.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="http://ftp14.FreeBSD.org/pub/FreeBSD/">http://ftp14.FreeBSD.org/pub/FreeBSD/</link>) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-au-ftp"/>Австрал</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@au.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.au.FreeBSD.org/pub/FreeBSD/">ftp://ftp.au.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp2.au.FreeBSD.org/pub/FreeBSD/">ftp://ftp2.au.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp3.au.FreeBSD.org/pub/FreeBSD/">ftp://ftp3.au.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-at-ftp"/>Австри</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@at.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.at.FreeBSD.org/pub/FreeBSD/">ftp://ftp.at.FreeBSD.org/pub/FreeBSD/</link> (ftp / ftpv6 / <link xlink:href="http://ftp.at.FreeBSD.org/pub/FreeBSD/">http://ftp.at.FreeBSD.org/pub/FreeBSD/</link> / <link xlink:href="http://ftp.at.FreeBSD.org/pub/FreeBSD/">http://ftp.at.FreeBSD.org/pub/FreeBSD/</link>) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-us-ftp"/>АНУ</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@us.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp1.us.FreeBSD.org/pub/FreeBSD/">ftp://ftp1.us.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp2.us.FreeBSD.org/pub/FreeBSD/">ftp://ftp2.us.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp3.us.FreeBSD.org/pub/FreeBSD/">ftp://ftp3.us.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp4.us.FreeBSD.org/pub/FreeBSD/">ftp://ftp4.us.FreeBSD.org/pub/FreeBSD/</link> (ftp / ftpv6 / <link xlink:href="http://ftp4.us.FreeBSD.org/pub/FreeBSD/">http://ftp4.us.FreeBSD.org/pub/FreeBSD/</link> / <link xlink:href="http://ftp4.us.FreeBSD.org/pub/FreeBSD/">http://ftp4.us.FreeBSD.org/pub/FreeBSD/</link>) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp5.us.FreeBSD.org/pub/FreeBSD/">ftp://ftp5.us.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp6.us.FreeBSD.org/pub/FreeBSD/">ftp://ftp6.us.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp8.us.FreeBSD.org/pub/FreeBSD/">ftp://ftp8.us.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp10.us.FreeBSD.org/pub/FreeBSD/">ftp://ftp10.us.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp11.us.FreeBSD.org/pub/FreeBSD/">ftp://ftp11.us.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp13.us.FreeBSD.org/pub/FreeBSD/">ftp://ftp13.us.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="http://ftp13.us.FreeBSD.org/pub/FreeBSD/">http://ftp13.us.FreeBSD.org/pub/FreeBSD/</link> / rsync) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp14.us.FreeBSD.org/pub/FreeBSD/">ftp://ftp14.us.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="http://ftp14.us.FreeBSD.org/pub/FreeBSD/">http://ftp14.us.FreeBSD.org/pub/FreeBSD/</link>) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp15.us.FreeBSD.org/pub/FreeBSD/">ftp://ftp15.us.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-am-ftp"/>Армен</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@am.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp1.am.FreeBSD.org/pub/FreeBSD/">ftp://ftp1.am.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="http://ftp1.am.FreeBSD.org/pub/FreeBSD/">http://ftp1.am.FreeBSD.org/pub/FreeBSD/</link> / rsync) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-br-ftp"/>Бразил</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@br.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp2.br.FreeBSD.org/FreeBSD/">ftp://ftp2.br.FreeBSD.org/FreeBSD/</link> (ftp / <link xlink:href="http://ftp2.br.FreeBSD.org/">http://ftp2.br.FreeBSD.org/</link>) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp3.br.FreeBSD.org/pub/FreeBSD/">ftp://ftp3.br.FreeBSD.org/pub/FreeBSD/</link> (ftp / rsync) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp4.br.FreeBSD.org/pub/FreeBSD/">ftp://ftp4.br.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-de-ftp"/>Герман</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>de-bsd-hubs@de.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.de.FreeBSD.org/pub/FreeBSD/">ftp://ftp.de.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp1.de.FreeBSD.org/freebsd/">ftp://ftp1.de.FreeBSD.org/freebsd/</link> (ftp / <link xlink:href="http://www1.de.FreeBSD.org/freebsd/">http://www1.de.FreeBSD.org/freebsd/</link> / <link xlink:href="rsync://rsync3.de.FreeBSD.org/freebsd/">rsync://rsync3.de.FreeBSD.org/freebsd/</link>) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp2.de.FreeBSD.org/pub/FreeBSD/">ftp://ftp2.de.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="http://ftp2.de.FreeBSD.org/pub/FreeBSD/">http://ftp2.de.FreeBSD.org/pub/FreeBSD/</link> / rsync) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp4.de.FreeBSD.org/FreeBSD/">ftp://ftp4.de.FreeBSD.org/FreeBSD/</link> (ftp / <link xlink:href="http://ftp4.de.FreeBSD.org/pub/FreeBSD/">http://ftp4.de.FreeBSD.org/pub/FreeBSD/</link>) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp5.de.FreeBSD.org/pub/FreeBSD/">ftp://ftp5.de.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp7.de.FreeBSD.org/pub/FreeBSD/">ftp://ftp7.de.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="http://ftp7.de.FreeBSD.org/pub/FreeBSD/">http://ftp7.de.FreeBSD.org/pub/FreeBSD/</link>) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp8.de.FreeBSD.org/pub/FreeBSD/">ftp://ftp8.de.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-gr-ftp"/>Грек</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@gr.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.gr.FreeBSD.org/pub/FreeBSD/">ftp://ftp.gr.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp2.gr.FreeBSD.org/pub/FreeBSD/">ftp://ftp2.gr.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-dk-ftp"/>Дани</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@dk.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.dk.FreeBSD.org/pub/FreeBSD/">ftp://ftp.dk.FreeBSD.org/pub/FreeBSD/</link> (ftp / ftpv6 / <link xlink:href="http://ftp.dk.FreeBSD.org/pub/FreeBSD/">http://ftp.dk.FreeBSD.org/pub/FreeBSD/</link> / <link xlink:href="http://ftp.dk.FreeBSD.org/pub/FreeBSD/">http://ftp.dk.FreeBSD.org/pub/FreeBSD/</link>) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-ie-ftp"/>Ирланд</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@ie.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp3.ie.FreeBSD.org/pub/FreeBSD/">ftp://ftp3.ie.FreeBSD.org/pub/FreeBSD/</link> (ftp / rsync) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-es-ftp"/>Испани</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@es.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.es.FreeBSD.org/pub/FreeBSD/">ftp://ftp.es.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="http://ftp.es.FreeBSD.org/pub/FreeBSD/">http://ftp.es.FreeBSD.org/pub/FreeBSD/</link>) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp3.es.FreeBSD.org/pub/FreeBSD/">ftp://ftp3.es.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-uk-ftp"/>Их Британи</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@uk.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.uk.FreeBSD.org/pub/FreeBSD/">ftp://ftp.uk.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp2.uk.FreeBSD.org/pub/FreeBSD/">ftp://ftp2.uk.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="rsync://ftp2.uk.FreeBSD.org/ftp.freebsd.org/pub/FreeBSD/">rsync://ftp2.uk.FreeBSD.org/ftp.freebsd.org/pub/FreeBSD/</link>) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp3.uk.FreeBSD.org/pub/FreeBSD/">ftp://ftp3.uk.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp4.uk.FreeBSD.org/pub/FreeBSD/">ftp://ftp4.uk.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp5.uk.FreeBSD.org/pub/FreeBSD/">ftp://ftp5.uk.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-ca-ftp"/>Канад</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@ca.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.ca.FreeBSD.org/pub/FreeBSD/">ftp://ftp.ca.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp2.ca.FreeBSD.org/pub/FreeBSD/">ftp://ftp2.ca.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-lv-ftp"/>Латви</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@lv.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.lv.FreeBSD.org/pub/FreeBSD/">ftp://ftp.lv.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="http://ftp.lv.FreeBSD.org/pub/FreeBSD/">http://ftp.lv.FreeBSD.org/pub/FreeBSD/</link>) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-lt-ftp"/>Литва</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@lt.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.lt.FreeBSD.org/pub/FreeBSD/">ftp://ftp.lt.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="http://ftp.lt.FreeBSD.org/pub/FreeBSD/">http://ftp.lt.FreeBSD.org/pub/FreeBSD/</link>) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-nl-ftp"/>Нидерланд</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@nl.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.nl.FreeBSD.org/pub/FreeBSD/">ftp://ftp.nl.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="http://ftp.nl.FreeBSD.org/os/FreeBSD/">http://ftp.nl.FreeBSD.org/os/FreeBSD/</link> / rsync) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp2.nl.FreeBSD.org/pub/FreeBSD/">ftp://ftp2.nl.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-no-ftp"/>Норвег</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@no.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.no.FreeBSD.org/pub/FreeBSD/">ftp://ftp.no.FreeBSD.org/pub/FreeBSD/</link> (ftp / rsync) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-ru-ftp"/>Орос</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@ru.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.ru.FreeBSD.org/pub/FreeBSD/">ftp://ftp.ru.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="http://ftp.ru.FreeBSD.org/FreeBSD/">http://ftp.ru.FreeBSD.org/FreeBSD/</link> / rsync) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp2.ru.FreeBSD.org/pub/FreeBSD/">ftp://ftp2.ru.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="http://ftp2.ru.FreeBSD.org/pub/FreeBSD/">http://ftp2.ru.FreeBSD.org/pub/FreeBSD/</link> / rsync) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp4.ru.FreeBSD.org/pub/FreeBSD/">ftp://ftp4.ru.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp5.ru.FreeBSD.org/pub/FreeBSD/">ftp://ftp5.ru.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="http://ftp5.ru.FreeBSD.org/pub/FreeBSD/">http://ftp5.ru.FreeBSD.org/pub/FreeBSD/</link> / rsync) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp6.ru.FreeBSD.org/pub/FreeBSD/">ftp://ftp6.ru.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-pl-ftp"/>Польш</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@pl.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.pl.FreeBSD.org/pub/FreeBSD/">ftp://ftp.pl.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para>ftp2.pl.FreeBSD.org</para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-sa-ftp"/>Саудын Араб</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>ftpadmin@isu.net.sa</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.isu.net.sa/pub/ftp.freebsd.org/">ftp://ftp.isu.net.sa/pub/ftp.freebsd.org/</link> (ftp) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-si-ftp"/>Словен</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@si.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.si.FreeBSD.org/pub/FreeBSD/">ftp://ftp.si.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-kr-ftp"/>Солонгос</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@kr.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.kr.FreeBSD.org/pub/FreeBSD/">ftp://ftp.kr.FreeBSD.org/pub/FreeBSD/</link> (ftp / rsync) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp2.kr.FreeBSD.org/pub/FreeBSD/">ftp://ftp2.kr.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="http://ftp2.kr.FreeBSD.org/pub/FreeBSD/">http://ftp2.kr.FreeBSD.org/pub/FreeBSD/</link>) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-tw-ftp"/>Тайвань</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@tw.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.tw.FreeBSD.org/pub/FreeBSD/">ftp://ftp.tw.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="ftp://ftp.tw.FreeBSD.org/pub/FreeBSD/">ftp://ftp.tw.FreeBSD.org/pub/FreeBSD/</link> / rsync / rsyncv6) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp2.tw.FreeBSD.org/pub/FreeBSD/">ftp://ftp2.tw.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="ftp://ftp2.tw.FreeBSD.org/pub/FreeBSD/">ftp://ftp2.tw.FreeBSD.org/pub/FreeBSD/</link> / <link xlink:href="http://ftp2.tw.FreeBSD.org/pub/FreeBSD/">http://ftp2.tw.FreeBSD.org/pub/FreeBSD/</link> / <link xlink:href="http://ftp2.tw.FreeBSD.org/pub/FreeBSD/">http://ftp2.tw.FreeBSD.org/pub/FreeBSD/</link> / rsync / rsyncv6) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp4.tw.FreeBSD.org/pub/FreeBSD/">ftp://ftp4.tw.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp5.tw.FreeBSD.org/pub/FreeBSD/">ftp://ftp5.tw.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp6.tw.FreeBSD.org/pub/FreeBSD/">ftp://ftp6.tw.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="http://ftp6.tw.FreeBSD.org/">http://ftp6.tw.FreeBSD.org/</link> / rsync) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp7.tw.FreeBSD.org/pub/FreeBSD/">ftp://ftp7.tw.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp8.tw.FreeBSD.org/pub/FreeBSD/">ftp://ftp8.tw.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp11.tw.FreeBSD.org/pub/FreeBSD/">ftp://ftp11.tw.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="http://ftp11.tw.FreeBSD.org/FreeBSD/">http://ftp11.tw.FreeBSD.org/FreeBSD/</link>) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp12.tw.FreeBSD.org/pub/FreeBSD/">ftp://ftp12.tw.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp13.tw.FreeBSD.org/pub/FreeBSD/">ftp://ftp13.tw.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp14.tw.FreeBSD.org/pub/FreeBSD/">ftp://ftp14.tw.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp15.tw.FreeBSD.org/pub/FreeBSD/">ftp://ftp15.tw.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-ua-ftp"/>Украйн</term>
    <listitem>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.ua.FreeBSD.org/pub/FreeBSD/">ftp://ftp.ua.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="http://ftp.ua.FreeBSD.org/pub/FreeBSD/">http://ftp.ua.FreeBSD.org/pub/FreeBSD/</link>) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp6.ua.FreeBSD.org/pub/FreeBSD/">ftp://ftp6.ua.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="http://ftp6.ua.FreeBSD.org/pub/FreeBSD">http://ftp6.ua.FreeBSD.org/pub/FreeBSD</link> / <link xlink:href="rsync://ftp6.ua.FreeBSD.org/FreeBSD/">rsync://ftp6.ua.FreeBSD.org/FreeBSD/</link>) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp7.ua.FreeBSD.org/pub/FreeBSD/">ftp://ftp7.ua.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-fi-ftp"/>Финланд</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@fi.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.fi.FreeBSD.org/pub/FreeBSD/">ftp://ftp.fi.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-fr-ftp"/>Франц</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@fr.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.fr.FreeBSD.org/pub/FreeBSD/">ftp://ftp.fr.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp1.fr.FreeBSD.org/pub/FreeBSD/">ftp://ftp1.fr.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="http://ftp1.fr.FreeBSD.org/pub/FreeBSD/">http://ftp1.fr.FreeBSD.org/pub/FreeBSD/</link> / rsync) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp3.fr.FreeBSD.org/pub/FreeBSD/">ftp://ftp3.fr.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp5.fr.FreeBSD.org/pub/FreeBSD/">ftp://ftp5.fr.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp6.fr.FreeBSD.org/pub/FreeBSD/">ftp://ftp6.fr.FreeBSD.org/pub/FreeBSD/</link> (ftp / rsync) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp7.fr.FreeBSD.org/pub/FreeBSD/">ftp://ftp7.fr.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp8.fr.FreeBSD.org/pub/FreeBSD/">ftp://ftp8.fr.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-hk-ftp"/>Хонг Конг</term>
    <listitem>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.hk.FreeBSD.org/pub/FreeBSD/">ftp://ftp.hk.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-cn-ftp"/>Хятад</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@cn.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.cn.FreeBSD.org/pub/FreeBSD/">ftp://ftp.cn.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-cz-ftp"/>Чех</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@cz.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.cz.FreeBSD.org/pub/FreeBSD/">ftp://ftp.cz.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="ftp://ftp.cz.FreeBSD.org/pub/FreeBSD/">ftp://ftp.cz.FreeBSD.org/pub/FreeBSD/</link> / <link xlink:href="http://ftp.cz.FreeBSD.org/pub/FreeBSD/">http://ftp.cz.FreeBSD.org/pub/FreeBSD/</link> / <link xlink:href="http://ftp.cz.FreeBSD.org/pub/FreeBSD/">http://ftp.cz.FreeBSD.org/pub/FreeBSD/</link> / rsync / rsyncv6) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp2.cz.FreeBSD.org/pub/FreeBSD/">ftp://ftp2.cz.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="http://ftp2.cz.FreeBSD.org/pub/FreeBSD/">http://ftp2.cz.FreeBSD.org/pub/FreeBSD/</link>) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-se-ftp"/>Швед</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@se.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.se.FreeBSD.org/pub/FreeBSD/">ftp://ftp.se.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp2.se.FreeBSD.org/pub/FreeBSD/">ftp://ftp2.se.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="rsync://ftp2.se.FreeBSD.org/">rsync://ftp2.se.FreeBSD.org/</link>) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp3.se.FreeBSD.org/pub/FreeBSD/">ftp://ftp3.se.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp4.se.FreeBSD.org/pub/FreeBSD/">ftp://ftp4.se.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="ftp://ftp4.se.FreeBSD.org/pub/FreeBSD/">ftp://ftp4.se.FreeBSD.org/pub/FreeBSD/</link> / <link xlink:href="http://ftp4.se.FreeBSD.org/pub/FreeBSD/">http://ftp4.se.FreeBSD.org/pub/FreeBSD/</link> / <link xlink:href="http://ftp4.se.FreeBSD.org/pub/FreeBSD/">http://ftp4.se.FreeBSD.org/pub/FreeBSD/</link> / <link xlink:href="rsync://ftp4.se.FreeBSD.org/pub/FreeBSD/">rsync://ftp4.se.FreeBSD.org/pub/FreeBSD/</link> / <link xlink:href="rsync://ftp4.se.FreeBSD.org/pub/FreeBSD/">rsync://ftp4.se.FreeBSD.org/pub/FreeBSD/</link>) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp6.se.FreeBSD.org/pub/FreeBSD/">ftp://ftp6.se.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="http://ftp6.se.FreeBSD.org/pub/FreeBSD/">http://ftp6.se.FreeBSD.org/pub/FreeBSD/</link>) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-ch-ftp"/>Швейцарь</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@ch.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.ch.FreeBSD.org/pub/FreeBSD/">ftp://ftp.ch.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="http://ftp.ch.FreeBSD.org/pub/FreeBSD/">http://ftp.ch.FreeBSD.org/pub/FreeBSD/</link>) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-nz-ftp"/>Шинэ Зеланд</term>
    <listitem>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.nz.FreeBSD.org/pub/FreeBSD/">ftp://ftp.nz.FreeBSD.org/pub/FreeBSD/</link> (ftp / <link xlink:href="http://ftp.nz.FreeBSD.org/pub/FreeBSD/">http://ftp.nz.FreeBSD.org/pub/FreeBSD/</link>) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-ee-ftp"/>Эстон</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@ee.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.ee.FreeBSD.org/pub/FreeBSD/">ftp://ftp.ee.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-jp-ftp"/>Япон</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@jp.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.jp.FreeBSD.org/pub/FreeBSD/">ftp://ftp.jp.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp2.jp.FreeBSD.org/pub/FreeBSD/">ftp://ftp2.jp.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp3.jp.FreeBSD.org/pub/FreeBSD/">ftp://ftp3.jp.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp4.jp.FreeBSD.org/pub/FreeBSD/">ftp://ftp4.jp.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp5.jp.FreeBSD.org/pub/FreeBSD/">ftp://ftp5.jp.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp6.jp.FreeBSD.org/pub/FreeBSD/">ftp://ftp6.jp.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp7.jp.FreeBSD.org/pub/FreeBSD/">ftp://ftp7.jp.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp8.jp.FreeBSD.org/pub/FreeBSD/">ftp://ftp8.jp.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp9.jp.FreeBSD.org/pub/FreeBSD/">ftp://ftp9.jp.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
  <varlistentry>
    <term><anchor xml:id="mirrors-za-ftp"/>Өмнөд Африк</term>
    <listitem>
      <para>Асуудлууд гарвал энэ домэйны администратор
      <email>hostmaster@za.FreeBSD.org</email>-т хандана уу.</para>
      <itemizedlist>
        <listitem>
          <para><link xlink:href="ftp://ftp.za.FreeBSD.org/pub/FreeBSD/">ftp://ftp.za.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp2.za.FreeBSD.org/pub/FreeBSD/">ftp://ftp2.za.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
        <listitem>
          <para><link xlink:href="ftp://ftp4.za.FreeBSD.org/pub/FreeBSD/">ftp://ftp4.za.FreeBSD.org/pub/FreeBSD/</link> (ftp) </para>
        </listitem>
      </itemizedlist>
    </listitem>
  </varlistentry>
</variablelist>
