<?xml version="1.0" encoding="utf-8"?>
<itemizedlist xmlns:xlink="http://www.w3.org/1999/xlink">
  <listitem>
    <anchor xml:id="central-www"/>
    <para>中央服务器</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.FreeBSD.org/">http://www.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-tw-www"/>
    <para>中国台湾</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.tw.FreeBSD.org/">http://www.tw.FreeBSD.org/</link>
        </para>
      </listitem>
      <listitem>
        <para>
          <link xlink:href="http://www2.tw.FreeBSD.org/">http://www2.tw.FreeBSD.org/</link>
        </para>
      </listitem>
      <listitem>
        <para>
          <link xlink:href="http://www4.tw.FreeBSD.org/">http://www4.tw.FreeBSD.org/</link>
        </para>
      </listitem>
      <listitem>
        <para><link xlink:href="http://www5.tw.FreeBSD.org/">http://www5.tw.FreeBSD.org/</link> (IPv6)</para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-hk-www"/>
    <para>中国香港</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.hk.FreeBSD.org/">http://www.hk.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-dk-www"/>
    <para>丹麦</para>
    <itemizedlist>
      <listitem>
        <para><link xlink:href="http://www.dk.FreeBSD.org/">http://www.dk.FreeBSD.org/</link> (IPv6)</para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-am-www"/>
    <para>亚美尼亚</para>
    <itemizedlist>
      <listitem>
        <para><link xlink:href="http://www1.am.FreeBSD.org/">http://www1.am.FreeBSD.org/</link> (IPv6)</para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-ru-www"/>
    <para>俄罗斯</para>
    <itemizedlist>
      <listitem>
        <para><link xlink:href="http://www.ru.FreeBSD.org/">http://www.ru.FreeBSD.org/</link> (IPv6)</para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-ca-www"/>
    <para>加拿大</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.ca.FreeBSD.org/">http://www.ca.FreeBSD.org/</link>
        </para>
      </listitem>
      <listitem>
        <para>
          <link xlink:href="http://www2.ca.FreeBSD.org/">http://www2.ca.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-za-www"/>
    <para>南非</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.za.FreeBSD.org/">http://www.za.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-at-www"/>
    <para>奥地利</para>
    <itemizedlist>
      <listitem>
        <para><link xlink:href="http://www.at.FreeBSD.org/">http://www.at.FreeBSD.org/</link> (IPv6)</para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-de-www"/>
    <para>德国</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.de.FreeBSD.org/">http://www.de.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-lv-www"/>
    <para>拉脱维亚</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.lv.FreeBSD.org/">http://www.lv.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-no-www"/>
    <para>挪威</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.no.FreeBSD.org/">http://www.no.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-cz-www"/>
    <para>捷克共和国</para>
    <itemizedlist>
      <listitem>
        <para><link xlink:href="http://www.cz.FreeBSD.org/">http://www.cz.FreeBSD.org/</link> (IPv6)</para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-si-www"/>
    <para>斯洛文尼亚</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.si.FreeBSD.org/">http://www.si.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-jp-www"/>
    <para>日本</para>
    <itemizedlist>
      <listitem>
        <para><link xlink:href="http://www.jp.FreeBSD.org/www.FreeBSD.org/">http://www.jp.FreeBSD.org/www.FreeBSD.org/</link> (IPv6)</para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-fr-www"/>
    <para>法国</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www1.fr.FreeBSD.org/">http://www1.fr.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-au-www"/>
    <para>澳大利亚</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.au.FreeBSD.org/">http://www.au.FreeBSD.org/</link>
        </para>
      </listitem>
      <listitem>
        <para>
          <link xlink:href="http://www2.au.FreeBSD.org/">http://www2.au.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-ie-www"/>
    <para>爱尔兰</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.ie.FreeBSD.org/">http://www.ie.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-se-www"/>
    <para>瑞典</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.se.FreeBSD.org/">http://www.se.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-ch-www"/>
    <para>瑞士</para>
    <itemizedlist>
      <listitem>
        <para><link xlink:href="http://www.ch.FreeBSD.org/">http://www.ch.FreeBSD.org/</link> (IPv6)</para>
      </listitem>
      <listitem>
        <para><link xlink:href="http://www2.ch.FreeBSD.org/">http://www2.ch.FreeBSD.org/</link> (IPv6)</para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-lt-www"/>
    <para>立陶宛</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.lt.FreeBSD.org/">http://www.lt.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-us-www"/>
    <para>美国</para>
    <itemizedlist>
      <listitem>
        <para><link xlink:href="http://www5.us.FreeBSD.org/">http://www5.us.FreeBSD.org/</link> (IPv6)</para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-fi-www"/>
    <para>芬兰</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.fi.FreeBSD.org/">http://www.fi.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-uk-www"/>
    <para>英国</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www1.uk.FreeBSD.org/">http://www1.uk.FreeBSD.org/</link>
        </para>
      </listitem>
      <listitem>
        <para>
          <link xlink:href="http://www3.uk.FreeBSD.org/">http://www3.uk.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-nl-www"/>
    <para>荷兰</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.nl.FreeBSD.org/">http://www.nl.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-es-www"/>
    <para>西班牙</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.es.FreeBSD.org/">http://www.es.FreeBSD.org/</link>
        </para>
      </listitem>
      <listitem>
        <para>
          <link xlink:href="http://www2.es.FreeBSD.org/">http://www2.es.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
</itemizedlist>
