<?xml version="1.0" encoding="iso-8859-1"?>
<itemizedlist xmlns:xlink="http://www.w3.org/1999/xlink">
  <listitem>
    <anchor xml:id="central-www"/>
    <para>Serveurs primaires</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.FreeBSD.org/">http://www.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-za-www"/>
    <para>Afrique du Sud</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.za.FreeBSD.org/">http://www.za.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-de-www"/>
    <para>Allemagne</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.de.FreeBSD.org/">http://www.de.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-am-www"/>
    <para>Armenia</para>
    <itemizedlist>
      <listitem>
        <para><link xlink:href="http://www1.am.FreeBSD.org/">http://www1.am.FreeBSD.org/</link> (IPv6)</para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-au-www"/>
    <para>Australie</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.au.FreeBSD.org/">http://www.au.FreeBSD.org/</link>
        </para>
      </listitem>
      <listitem>
        <para>
          <link xlink:href="http://www2.au.FreeBSD.org/">http://www2.au.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-at-www"/>
    <para>Autriche</para>
    <itemizedlist>
      <listitem>
        <para><link xlink:href="http://www.at.FreeBSD.org/">http://www.at.FreeBSD.org/</link> (IPv6)</para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-ca-www"/>
    <para>Canada</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.ca.FreeBSD.org/">http://www.ca.FreeBSD.org/</link>
        </para>
      </listitem>
      <listitem>
        <para>
          <link xlink:href="http://www2.ca.FreeBSD.org/">http://www2.ca.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-dk-www"/>
    <para>Danemark</para>
    <itemizedlist>
      <listitem>
        <para><link xlink:href="http://www.dk.FreeBSD.org/">http://www.dk.FreeBSD.org/</link> (IPv6)</para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-es-www"/>
    <para>Espagne</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.es.FreeBSD.org/">http://www.es.FreeBSD.org/</link>
        </para>
      </listitem>
      <listitem>
        <para>
          <link xlink:href="http://www2.es.FreeBSD.org/">http://www2.es.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-fi-www"/>
    <para>Finlande</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.fi.FreeBSD.org/">http://www.fi.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-fr-www"/>
    <para>France</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www1.fr.FreeBSD.org/">http://www1.fr.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-hk-www"/>
    <para>Hong-Kong</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.hk.FreeBSD.org/">http://www.hk.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-ie-www"/>
    <para>Irlande</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.ie.FreeBSD.org/">http://www.ie.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-jp-www"/>
    <para>Japon</para>
    <itemizedlist>
      <listitem>
        <para><link xlink:href="http://www.jp.FreeBSD.org/www.FreeBSD.org/">http://www.jp.FreeBSD.org/www.FreeBSD.org/</link> (IPv6)</para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-lv-www"/>
    <para>Lettonie</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.lv.FreeBSD.org/">http://www.lv.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-lt-www"/>
    <para>Lituanie</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.lt.FreeBSD.org/">http://www.lt.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-no-www"/>
    <para>Norvège</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.no.FreeBSD.org/">http://www.no.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-nl-www"/>
    <para>Pays-Bas</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.nl.FreeBSD.org/">http://www.nl.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-cz-www"/>
    <para>République Tchèque</para>
    <itemizedlist>
      <listitem>
        <para><link xlink:href="http://www.cz.FreeBSD.org/">http://www.cz.FreeBSD.org/</link> (IPv6)</para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-uk-www"/>
    <para>Royaume-Uni</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www1.uk.FreeBSD.org/">http://www1.uk.FreeBSD.org/</link>
        </para>
      </listitem>
      <listitem>
        <para>
          <link xlink:href="http://www3.uk.FreeBSD.org/">http://www3.uk.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-ru-www"/>
    <para>Russie</para>
    <itemizedlist>
      <listitem>
        <para><link xlink:href="http://www.ru.FreeBSD.org/">http://www.ru.FreeBSD.org/</link> (IPv6)</para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-si-www"/>
    <para>Slovénie</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.si.FreeBSD.org/">http://www.si.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-se-www"/>
    <para>Suède</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.se.FreeBSD.org/">http://www.se.FreeBSD.org/</link>
        </para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-ch-www"/>
    <para>Suisse</para>
    <itemizedlist>
      <listitem>
        <para><link xlink:href="http://www.ch.FreeBSD.org/">http://www.ch.FreeBSD.org/</link> (IPv6)</para>
      </listitem>
      <listitem>
        <para><link xlink:href="http://www2.ch.FreeBSD.org/">http://www2.ch.FreeBSD.org/</link> (IPv6)</para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-tw-www"/>
    <para>Taïwan</para>
    <itemizedlist>
      <listitem>
        <para>
          <link xlink:href="http://www.tw.FreeBSD.org/">http://www.tw.FreeBSD.org/</link>
        </para>
      </listitem>
      <listitem>
        <para>
          <link xlink:href="http://www2.tw.FreeBSD.org/">http://www2.tw.FreeBSD.org/</link>
        </para>
      </listitem>
      <listitem>
        <para>
          <link xlink:href="http://www4.tw.FreeBSD.org/">http://www4.tw.FreeBSD.org/</link>
        </para>
      </listitem>
      <listitem>
        <para><link xlink:href="http://www5.tw.FreeBSD.org/">http://www5.tw.FreeBSD.org/</link> (IPv6)</para>
      </listitem>
    </itemizedlist>
  </listitem>
  <listitem>
    <anchor xml:id="mirrors-us-www"/>
    <para>USA</para>
    <itemizedlist>
      <listitem>
        <para><link xlink:href="http://www5.us.FreeBSD.org/">http://www5.us.FreeBSD.org/</link> (IPv6)</para>
      </listitem>
    </itemizedlist>
  </listitem>
</itemizedlist>
